# Site Settings
title: "Economic Analysis Documentation"
description: "Comprehensive guides and resources for economic analysis."
baseurl: ""
url: "https://yourdomain.com"

# Navigation Bar
theme:
  name: material
  palette:
    primary: "indigo"
    accent: "cyan"
  features:
    - navigation.tabs
    - navigation.top
  logo: images/logo.png
  favicon: images/favicon.ico

nav:
  - Home: index.md
  - Blog:
      - Categories: blog/categories.md
      - Archives: blog/archives.md
  - Models:
      - Macroeconomic: models/macroeconomic.md
      - Microeconomic: models/microeconomic.md
      - Forecasting: models/forecasting.md
  - About:
      - Contact: about/contact.md

# Plugins
plugins:
  - search
  - mkdocs-material
  - toc:
      permalink: true
  - git-revision-date
  - redirects

# Extra Configurations
extra:
  search:
    language: "en"
    separator: "[\\s\\-]+"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheStatsProject/finance-models-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourprofile

# Repository Information
repo_name: "TheStatsProject/finance-models-docs"
repo_url: "https://github.com/TheStatsProject/finance-models-docs"

# Additional Configurations
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - codehilite:
      guess_lang: false
