site_name: Finance Models
site_description: Articles and models on macroeconomic and financial analysis
site_url: https://TheStatsProject.github.io/finance-models-docs/

repo_url: https://github.com/TheStatsProject/finance-models-docs
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light and dark mode with toggle
    - scheme: default                                   # default light mode :contentReference[oaicite:0]{index=0}
      primary: indigo                                   # Google Material primary color :contentReference[oaicite:1]{index=1}
      accent: amber                                     # Google Material accent color :contentReference[oaicite:2]{index=2}
      toggle:
        icon: material/weather-night                    # icon for dark mode toggle :contentReference[oaicite:3]{index=3}
        name: Switch to dark mode
    - scheme: slate                                     # dark mode palette :contentReference[oaicite:4]{index=4}
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny                    # icon for light mode toggle :contentReference[oaicite:5]{index=5}
        name: Switch to light mode

  # Enable Material theme enhancements
  features:
    - navigation.indexes    # make section index pages for nav sections :contentReference[oaicite:6]{index=6}
    - navigation.tabs       # show top-level nav as horizontal tabs :contentReference[oaicite:7]{index=7}
    - navigation.instant    # instant page loading via partial reloads :contentReference[oaicite:8]{index=8}
    - search.suggest        # show search suggestions in real time :contentReference[oaicite:9]{index=9}

  font:
    text: Lexend              # use a custom text font :contentReference[oaicite:10]{index=10}

  icon:
    repo: fontawesome/brands/github  # custom repository icon :contentReference[oaicite:11]{index=11}

plugins:
  - search                     # default search plugin :contentReference[oaicite:12]{index=12}
  - blog                       # built-in blog plugin for automatic archives :contentReference[oaicite:13]{index=13}
  - tags                       # categorize posts and pages via tags plugin :contentReference[oaicite:14]{index=14}

extra:
  social:                     # add social icons in the header/footer :contentReference[oaicite:15]{index=15}
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<your-handle>
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/<your-id>

nav:                          # define precise navigation order :contentReference[oaicite:16]{index=16}
  - Home: index.md
  - Home: index.md
  - Example Article: example-article.md


extra_css:
  - stylesheets/extra.css      # optional custom CSS overrides :contentReference[oaicite:17]{index=17}

extra_javascript:
  - javascripts/extra.js       # optional custom JS for extended behavior :contentReference[oaicite:18]{index=18}

use_directory_urls: true      # generate clean URLs (no .html) :contentReference[oaicite:19]{index=19}

# Show last updated timestamp on each page
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - meta

plugins:
  - git-revision-date-localized:   # show last updated dates :contentReference[oaicite:20]{index=20}
      locale: en

