site_name: Finance Models
site_description: Articles and models on macroeconomic and financial analysis
site_url: https://TheStatsProject.github.io/finance-models-docs/

repo_url: https://github.com/TheStatsProject/finance-models-docs
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date-localized
  - tags
  - rss

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<your-handle>
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/<your-id>

nav:
  - Home: index.md
  - Blog:
      - Home: blog/index.md
  - Articles:
      - Model A: articles/model_a.md
      - Model B: articles/model_b.md
  - About: about/about.md
  - Contact: about/contact.md

use_directory_urls: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - meta

plugins:
  - git-revision-date-localized:   # show last updated dates :contentReference[oaicite:20]{index=20}
      locale: en

