# Site Information
site_name: "Finance Models Documentation"
site_description: "Documentation for economic and financial models"
site_url: "https://TheStatsProject.github.io/finance-models-docs"
repo_name: "TheStatsProject/finance-models-docs"
repo_url: "https://github.com/TheStatsProject/finance-models-docs"

# Theme Configuration
theme:
  name: material
  palette:
    primary: "indigo"
    accent: "cyan"
  features:
    - navigation.tabs
    - navigation.top
  logo: images/logo.png
  favicon: images/favicon.ico

# Navigation Bar
nav:
  - Home: index.md
  - Blog:
      - Categories: blog/categories.md
      - Archives: blog/archives.md
  - Models:
      - Macroeconomic: models/macroeconomic.md
      - Microeconomic: models/microeconomic.md
      - Forecasting: models/forecasting.md
  - About:
      - Contact Us: about/contact.md

# Plugins
plugins:
  - mkdocs-material
  - search
  - redirects

# Markdown Extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite:
      guess_lang: false
