name: Deploy MkDocs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo, preserving the GITHUB_TOKEN for authenticated pushes
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '^3.9'

      # 3. Cache pip downloads to speed up installs
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install all dependencies from requirements.txt
      - name: Install dependencies
        env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    if [ -f "requirements.txt" ]; then
      pip install -r requirements.txt --extra-index-url https://$GITHUB_TOKEN@github.com/TheStatsProject/mkdocs-tags.git
    else
      echo "requirements.txt not found!"
      exit 1
    fi
    
      # 5. Lint MkDocs configuration to catch errors early
      - name: Lint MkDocs config
        run: mkdocs build --config-file mkdocs.yml --strict

      # 6. Build the MkDocs site into a clean "site/" directory
      - name: Build MkDocs site
        run: mkdocs build --site-dir site

      # 7. Deploy to GitHub Pages via peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # (Optional) Add your custom domain:
          # cname: finance.example.com

      # 8. Notify on deployment success or failure
      - name: Notify on Deployment
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "The deployment was successful!"
          else
            echo "The deployment failed!"
          fi
