name: Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-redirects  # Install the missing plugin

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
